version: "3.3"

services:
  s_rabbitmq:
    container_name: c_rabbitmq
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15672:15672"

  s_database:
    container_name: c_database
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Password123.
      POSTGRES_USER: postgres
      POSTGRES_DB: crawler
    ports:
      - "5432:5432"
    
  s_webapi:
    container_name: c_webapi
    image: crawler.webapi
    build:
      context: .
      dockerfile: src/Crawler.WebAPI/Dockerfile
    ports:
      - "8080:80"
    depends_on: 
      - s_database
      - s_rabbitmq

  s_pagedownloader:
    container_name: c_pagedownloader
    image: crawler.pagedownloader
    build:
      context: .
      dockerfile: src/Crawler.PageDownloader/Dockerfile
    depends_on:
      - s_database
      - s_rabbitmq
  
  s_linkextractor:
    container_name: c_linkextractor
    image: crawler.linkextractor
    build:
      context: .
      dockerfile: src/Crawler.LinkExtractor/Dockerfile
    depends_on:
      - s_database
      - s_rabbitmq
